### ISSUE TITLE
[Feature Request] Use a OBEX transfer service and accept receiving files

### ISSUE THREAD

**Issue by ksharindam** [raspberrypi-ui/lxplug-bluetooth#10]
I want to use this plugin to use a OBEX transfer service and when other device (e.g mobile) tries to send files, a pop up should open to accept receiving files.
So that , we dont need blueman anymore.

**Comment by spl237** [comment]
Unfortunately, adding OBEX is a huge pile of additional work, and the use case you mention isn't really one needed by enough people to justify it. I have no objections to adding OBEX at some point, but it would be such a low priority compared to pretty much everything else I need to do that it isn't likely to happen.

**Comment by ksharindam** [comment]
@spl237 For the last few days, I am trying to understand GDBus and bluez. 
And I have been able to create a commandline test program (obex.c) that can receive files over bluetooth.
It will take more time to add GUI, add error checking, and embedding the code in bluetooth plugin.
When It will be done, i will create a pull request.
