### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by ranma** [raspberrypi-ui/lxplug-bluetooth#15]
From investigation on https://github.com/raspberrypi/linux/issues/2810#issuecomment-792247800

I think it might be the lxplug-bluetooth plugin that is causing the lxpanel memory leak that is causing issues with my Pi3B+ grinding to a halt from OOM.

htop over ssh left running showed lxpanel using most of the memory:
```
  1  [||||||||                                        13.0%]   Tasks: 78, 157 thr; 3 running
  2  [|||||||||                                       15.3%]   Load average: 39.39 40.12 37.97 
  3  [|||||||||                                       14.3%]   Uptime: 07:53:55
  4  [||||||||||                                      16.8%]
  Mem[||||||||||||||||||||||||||||||||||||||||||||881M/924M]
  Swp[||||||||||||||||||||||||||||||||||||||||100.0M/100.0M]

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command                                                         
  457 grafana    20   0  934M 10728     0 S 32.2  1.1 29:40.85 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pid
  451 influxdb   20   0  978M  9476     0 D 28.4  1.0 35:29.89 /usr/bin/influxd -config /etc/influxdb/influxdb.conf
  494 grafana    20   0  934M 10728     0 R 20.4  1.1 15:36.50 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pid
  731 grafana    20   0  934M 10728     0 S 11.6  1.1  9:18.06 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pid
 1347 influxdb   20   0  978M  9476     0 D  6.1  1.0  5:24.33 /usr/bin/influxd -config /etc/influxdb/influxdb.conf
[...]
  795 pi         20   0  636M 39568     0 D  1.0  4.2  3:43.82 /usr/lib/chromium-browser/chromium-browser-v7 --force-renderer-a
 1282 pi         20   0  429M 72396   372 D  0.8  7.6  4:00.12 /usr/lib/chromium-browser/chromium-browser-v7 --type=renderer --
[...]
 760 pi         20   0 1012M  591M     0 D  0.4 64.0 28:24.12 lxpanel --profile LXDE-pi
```

Putting lxpanel into a cgroup memory jail solved the lockup issue and confirmed that lxpanel was the culprit.
gdb + coredump seems to implicate the bluetooth plugin
```
(gdb) attach 3924
Attaching to program: /usr/bin/lxpanel, process 3924
[New LWP 3928]
[New LWP 3942]
[New LWP 3948]
[New LWP 3988]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x73822510 in g_dbus_object_get_object_path@plt () from /usr/lib/arm-linux-gnueabihf/lxpanel/plugins/bluetooth.so
(gdb) bt
#0  0x73822510 in g_dbus_object_get_object_path@plt () from /usr/lib/arm-linux-gnueabihf/lxpanel/plugins/bluetooth.so
#1  0x73824ae0 in ?? () from /usr/lib/arm-linux-gnueabihf/lxpanel/plugins/bluetooth.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) gcore lxpanel.core
warning: target file /proc/3924/cmdline contained unexpected null characters
warning: Memory read failed for corefile section, 1048576 bytes at 0x60aff000.
warning: Memory read failed for corefile section, 1048576 bytes at 0x64aff000.
warning: Memory read failed for corefile section, 1048576 bytes at 0x68aff000.
warning: Memory read failed for corefile section, 1048576 bytes at 0x6cb00000.
warning: Memory read failed for corefile section, 135168 bytes at 0x6dd00000.
warning: Memory read failed for corefile section, 1048576 bytes at 0x6df00000.
warning: Memory read failed for corefile section, 135168 bytes at 0x6e700000.
warning: Memory read failed for corefile section, 1048576 bytes at 0x6e8ff000.
warning: Memory read failed for corefile section, 1048576 bytes at 0x6f100000.
warning: Memory read failed for corefile section, 135168 bytes at 0x6f900000.
warning: Memory read failed for corefile section, 393216 bytes at 0x6fa30000.
warning: Memory read failed for corefile section, 237568 bytes at 0x6fac5000.
warning: Memory read failed for corefile section, 135168 bytes at 0x70300000.
warning: Memory read failed for corefile section, 4096 bytes at 0x70465000.
warning: Memory read failed for corefile section, 1048576 bytes at 0x70468000.
warning: Memory read failed for corefile section, 135168 bytes at 0x74600000.
warning: Memory read failed for corefile section, 8192 bytes at 0x75b32000.
warning: Memory read failed for corefile section, 12288 bytes at 0x7639d000.
warning: Memory read failed for corefile section, 131072 bytes at 0x76ed6000.
warning: Memory read failed for corefile section, 135168 bytes at 0x7ea79000.
Saved corefile lxpanel.core
```

Looking at just strings in the corefile is just an indication, but also points a bit into too many bluetooth device properties being kept in memory
```
$ ls -lh lxpanel.core 
-rw-r--r-- 1 pi pi 432M Mar  7 10:37 lxpanel.core
$ strings lxpanel.core  | sort | uniq -c | sort -n -k1 -r | head -20
   6272 :1.18
   4376 daRvPaRv
   2569 org.bluez.Device1
   2414 org.freedesktop.DBus.Properties
   2080 org.freedesktop.DBus.Introspectable
   1595 RSSI
   1094 UUIDs
   1094 Alias
   1094 AddressType
   1094 Address
   1092 Trusted
   1092 ServicesResolved
   1092 Paired
   1092 LegacyPairing
   1092 Connected
   1092 Blocked
   1092 Adapter
    980 MXo=
    972 ManufacturerData
    888 /org/bluez/hci0
```

I think I see some missing calls to g_variant_unref  in cb_interface_properties, which could explain leaking memory.

**Comment by ranma** [comment]
Unfortunately libunwind appears to be non-functional (SEGFAULT in _ULarm_step) which rules out using `heaptrack`.
However some simple "lets make cb_interface_properties not do anything" changes shows that indeed cb_interface_properties is a top contender and in particular commenting out `update_device_list(bt);` seems to curb the memory, narrowing down the culprit.

**Comment by ranma** [comment]
`update_device_list` is actually fully rebuilding the lists of paired/unpaired devices by enumerating over all devices.
This is done on any interface property update of any bt device, which is at least wasteful work, in particular when the `Paired` property values didn't change.
And in particular there is one property which changes all the time: `RSSI`

**Comment by ranma** [comment]
I managed to get `heaptrack` to work after fixing a SEGFAULT bug in libunwind by commenting out the offending code for non-EABI support. However, while heaptrack is much faster than valgrinds massif, it still is too slow and DBus keeps running into timeout, so it doesn't manage to initialize the connection and event listeners. :(

**Comment by spl237** [comment]
The actual amount of work done in rebuilding the device lists isn't huge, and you need to monitor for property changes other than the Paired ones - for example, the capabilities and services of each device are not always correct when it is first detected. Also, it is less complex to just delete and rebuild than to go through and match up the changed device and update its information - plus doing it this way means the lists cannot get out of sync with reality due to an error. There is an argument that perhaps the device lists should only be updated while the Add or Remove dialogs are on the screen rather than all the time, but I don't see much wrong with the actual mechanism of the update. I will review for memory leaks though.

**Comment by ranma** [comment]
I found some additional g_free issues in the meantime:
DEBUG prints have a leak: https://github.com/ranma/lxplug-bluetooth/commit/ff38403ac397d1b1539f235c3fb79348a53b33cb (only relevant when DEBUG_BT env is set)
leak in find_path (and minor one in handle_pair): https://github.com/ranma/lxplug-bluetooth/commit/b6c0e02429d1f48e62c217f2d34b17ecffcc439c

**Comment by ranma** [comment]
> The actual amount of work done in rebuilding the device lists isn't huge, and you need to monitor for property changes other than the Paired ones - for example, the capabilities and services of each device are not always correct when it is first detected. Also, it is less complex to just delete and rebuild than to go through and match up the changed device and update its information - plus doing it this way means the lists cannot get out of sync with reality due to an error. There is an argument that perhaps the device lists should only be updated while the Add or Remove dialogs are on the screen rather than all the time, but I don't see much wrong with the actual mechanism of the update.

The one thing that I see that might be an issue:
How does the dialog react to the list changing while the user is interacting with it?
At least there is probably a small race between storing the current selection, updating the lists and then restoring the current selection. Re-rendering also may take time.

In my case, the list rebuild can be triggered multiple times per second (every time a beacon is seen and the RSSI attribute changes).

**Comment by spl237** [comment]
It isn't an issue from the user's perspective, as the only interaction they have is to select an item in the list, and that is preserved while the list is rebuilt anyway. I seem to recall that when I first wrote this code, I tried to update the existing lists rather than rebuilding, and the resulting code was complex and not particularly reliable. The same approach is used in the wireless network plugin - delete the existing list and start again; the small overhead in terms of work needed is worth it to make sure you don't get any out-of-sync problems.

**Comment by spl237** [comment]
Should have been fixed by latest checkin.

Incidentally - on my Pi, I only get cb_interface_changed callbacks while the Bluetooth is actively scanning for new devices (i.e. the "add device" dialog is open) - they do not occur when scanning is not in progress, so it is odd that you are seeing them all the time. Are you using non-standard BT hardware, like an external dongle?

**Comment by ranma** [comment]
I'm using the regular built-in bluetooth.

My python code looks like this:
```
#!/usr/bin/python3

import dbus
import time

from dbus.exceptions import DBusException
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import GLib
from influxdb import InfluxDBClient

class SystemBusListener(object):

    def __init__(self):
        self.bus = dbus.SystemBus()
        self.db = InfluxDBClient(database="foobar")

        # Listen for run-time changes
        self.bus.add_signal_receiver(
            self.interfaces_added, bus_name="org.bluez",
            dbus_interface="org.freedesktop.DBus.ObjectManager",
            signal_name="InterfacesAdded")

        self.bus.add_signal_receiver(
            self.property_changed, bus_name="org.bluez",
            dbus_interface="org.freedesktop.DBus.Properties",
            signal_name="PropertiesChanged",
            path_keyword="path")

        # Initial scan for interfaces
        om = dbus.Interface(self.bus.get_object("org.bluez", '/'),
                            "org.freedesktop.DBus.ObjectManager")
        objects = om.GetManagedObjects()
        for path, interfaces in objects.items():
            self.interfaces_added(path, interfaces)

    def ruuvi_beacon(self, path, data):
        print("Ruuvi beacon [%s]: %r" % (path, data))
        if data[0] == 3:
          humidity = data[1] / 2
          temperature = (data[2] & 0x7f) + data[3] / 100
          if data[2] & 0x80:
              temperature = -temperature
          pressure = (data[4] * 0x100 + data[5] + 50000) / 100
          battery = (data[12] * 0x100 + data[13]) / 1000
          print("Humdity: %.1f Temp: %.2f Pressure: %d BAT: %.3f" % (humidity, temperature, pressure, battery))
          self.db.write_points([{
               "measurement": "humidity",
               "fields": {
                 "Float_value": humidity,
               },
          }, {
               "measurement": "temperature",
               "fields": {
                 "Float_value": temperature,
               },
          }, {
               "measurement": "pressure",
               "fields": {
                 "Float_value": pressure,
               },
          }, {
               "measurement": "battery_volt",
               "fields": {
                 "Float_value": battery,
               },
          }], time_precision='s', tags={
              "source": "ruuvi:" + path,
          })

    def property_changed(self, interface, changed, invalidated, path):
        iface = interface[interface.rfind(".") + 1:]
        for name, value in changed.items():
            val = str(value)
            if name in ["RSSI", "TxPower"]:
                continue
            if (name == "ManufacturerData"
                and isinstance(value, dbus.Dictionary)
                and value.get(0x499)):
                self.ruuvi_beacon(path, value.get(0x499))
            elif name == "ManufacturerData":
                print("Unkown ManufacturerData: %s %r" % (path, value.keys()))
            else:
                print("{%s.PropertyChanged} [%s] %s = %s" % (
                    iface, path, name, val))

    def device_added(self, path, iface, props):
        print("Device added: %s %s" % (iface, path))

    def adapter_added(self, path, iface, props):
        obj = self.bus.get_object("org.bluez", path)
        props = dbus.Interface(obj, "org.freedesktop.DBus.Properties")
        props.Set(iface, "Powered", dbus.Boolean(1))
        adapter = dbus.Interface(obj, iface)
        try:
          # Start discovery of BLE devices on this adapter
          adapter.SetDiscoveryFilter({"Transport": "le"})
          adapter.StartDiscovery()
        except DBusException:
          pass

    def interfaces_added(self, path, interfaces):
        for iface, props in interfaces.items():
            if iface == "org.bluez.Adapter1":
                self.adapter_added(path, iface, props)
            elif iface == "org.bluez.Device1":
                self.device_added(path, iface, props)


def main():
    DBusGMainLoop(set_as_default=True)

    listener = SystemBusListener()

    loop = GLib.MainLoop()
    loop.run()


if __name__ == '__main__':
    main()
```

**Comment by spl237** [comment]
Ah, right - so you're not seeing that in the plugin; you are seeing it in your own application. That would make sense - your application puts the hardware into scan mode and leaves it there all the time; the plugin only puts the hardware in scan mode while the add devices window is open. So there's no issue with this causing constant CPU load in the plugin.

**Comment by ranma** [comment]
I've finally got valgrind running properly (also this time on the Pi4, which is just much faster).
I'll send you another pull request for more leaks soon. ;)

**Comment by ranma** [comment]
> Ah, right - so you're not seeing that in the plugin; you are seeing it in your own application. That would make sense - your application puts the hardware into scan mode and leaves it there all the time; the plugin only puts the hardware in scan mode while the add devices window is open. So there's no issue with this causing constant CPU load in the plugin.

Good point. I guess I should switch my python code to disable scanning after some period (once all Ruuvis have been found).

**Comment by ranma** [comment]
So apparently when I stop discovery I stop getting the BLE  beacons, so I can't do that...

Anyway, I left lxpanel running over night and with https://github.com/ranma/lxplug-bluetooth/commit/0e088731fb5d29b1404ebba7f6d095637c533876 I don't see any further memory growth, it's now stable.
